# keywords.py
# Nova Programming Language - Complete Keywords

KEYWORDS = {
    # Page Structure
    'page',
    'title',
    'icon',
    'theme',
    'language',
    
    # Text Elements
    'text',
    'heading',
    'subtitle',
    'small',
    'quote',
    'code',
    'link',
    'label',
    
    # Media Elements
    'image',
    'video',
    'audio',
    'gallery',
    'slideshow',
    
    # Layout Elements
    'container',
    'box',
    'card',
    'panel',
    'popup',
    'navbar',
    'footer',
    'sidebar',
    'section',
    'group',
    'row',
    'column',
    'grid',
    'tabs',
    'tab',
    
    # Input Elements
    'input',
    'number',
    'password',
    'email',
    'search',
    'slider',
    'checkbox',
    'radio',
    'dropdown',
    'date',
    'time',
    'colour',
    'upload',
    'textarea',
    
    # Buttons
    'button',
    'iconbutton',
    'floatingbutton',
    
    # Positioning
    'position',
    'center',
    'left',
    'right',
    'top',
    'bottom',
    'width',
    'height',
    'padding',
    'margin',
    
    # Styling
    'background',
    'textcolour',
    'bordercolour',
    'hovercolour',
    'pressedcolour',
    'transparent',
    'gradient',
    'font',
    'textsize',
    'bold',
    'italic',
    'underline',
    'roundcorners',
    'shadow',
    'border',
    'opacity',
    'blur',
    
    # Animations
    'animate',
    'fade',
    'slide',
    'grow',
    'rotate',
    'bounce',
    'spin',
    
    # Variables
    'remember',
    'load',
    'delete',
    'forget',
    'set',
    'make',
    'increase',
    'decrease',
    'toggle',
    'clear',
    'swap',
    
    # Math
    'add',
    'subtract',
    'multiply',
    'divide',
    'power',
    'squareroot',
    'round',
    'random',
    'minimum',
    'maximum',
    'mod',
    'absolute',
    'floor',
    'ceiling',
    
    # Logic
    'if',
    'otherwise',
    'elif',
    'repeat',
    'repeatwhile',
    'stop',
    'continue',
    'and',
    'or',
    'not',
    
    # Events
    'whenpageopens',
    'whenpagecloses',
    'whenclicked',
    'whendoubleclicked',
    'whenhovered',
    'whenhoverends',
    'whenmousemoves',
    'whenmousewheel',
    'whenkeypressed',
    'whenkeyreleased',
    'whenenterpressed',
    'whenescapepressed',
    'whenspacepressed',
    'wheninputchanged',
    'whensubmitted',
    'when',
    'whenblurred',
    'whenscrolled',
    
    # Navigation
    'gotopage',
    'goback',
    'refresh',
    'opentab',
    'download',
    'printpage',
    'openwebsite',
    'sharepage',
    'copylink',
    
    # Storage
    'getfromserver',
    'sendtoserver',
    'puttoserver',
    'deletefromserver',
    'fetch',
    'database',
    'connectdatabase',
    'savedatabase',
    'loaddatabase',
    'updatedatabase',
    'deletedatabase',
    'sessionsave',
    'cookie',
    
    # UI
    'askuser',
    'alert',
    'confirm',
    'notification',
    'copy',
    'paste',
    'toast',
    'progress',
    'loading',
    
    # Mouse Events
    'whenrightclicked',
    'whenhoverends',
    'whilehovering',
    'whenmousemoves',
    'whenmousewheel',
    'mouseposition',
    
    # Keyboard Events
    'whenkeyreleased',
    'whenenterpressed',
    'whenescapepressed',
    'whenspacepressed',
    'key',
    'shiftpressed',
    'controlpressed',
    'altpressed',
    
    # Touch Events
    'whentapped',
    'whendoubletapped',
    'whenlongpressed',
    'whenswipedleft',
    'whenswipedright',
    'whenswipedup',
    'whenswipeddown',
    'devicetilted',
    'deviceshaken',
    
    # Colors
    'backgroundcolour',
    'bordercolour',
    'shadowcolour',
    'hovercolour',
    'pressedcolour',
    'transparent',
    
    # UI Elements
    'textbox',
    'answerbox',
    'canvas',
    
    # States
    'visible',
    'hidden',
    'enabled',
    'disabled',
    'clickable',
    'locked',
    'selected',
    'focused',
    'show',
    'hide',
    'enable',
    'disable',
    
    # Transformations
    'moveto',
    'moveby',
    'shrink',
    'fliphorizontal',
    'flipvertical',
    'fadein',
    'fadeout',
    'shake',
    
    # Variable Operations
    'make',
    'set',
    'increase',
    'decrease',
    'toggle',
    'clear',
    'swap',
    
    # String Operations
    'uppercase',
    'lowercase',
    'capitalize',
    'trim',
    'replace',
    'contains',
    'startswith',
    'endswith',
    'lengthof',
    
    # Math Operations (short forms)
    'mod',
    'absolute',
    'floor',
    'ceiling',
    
    # Lists
    'makelist',
    'additem',
    'removeitem',
    'insertitem',
    'sort',
    'reverse',
    'shuffle',
    'clearlist',
    'listlength',
    'containsitem',
    
    # Files
    'uploadfile',
    'downloadfile',
    'savefile',
    'openfile',
    'deletefile',
    'renamefile',
    
    # Web
    'openwebsite',
    'refreshpage',
    'sharepage',
    'copylink',
    
    # Database
    'connectdatabase',
    'disconnectdatabase',
    'savedatabase',
    'loaddatabase',
    'updatedatabase',
    'deletedatabase',
    'sendrequest',
    'receiverequest',
    
    # Auth
    'login',
    'logout',
    'signup',
    'encrypt',
    'decrypt',
    'hash',
    'verifypassword',
    'generatetoken',
    
    # Time
    'wait',
    'every',
    'currenttime',
    'currentdate',
    'timer',
    'stoptimer',
    'countdown',
    
    # Media Control
    'play',
    'pause',
    'stop',
    'mute',
    'volume',
    'fullscreen',
    'camera',
    'takephoto',
    'recordvideo',
    'microphone',
    'recordaudio',
    
    # Additional Keywords
    'and',
    'or',
    'not',
    'true',
    'false',
    'to',
    'as',
    'from',
    'of',
    'with',
    'for',
    'while',
    'min',
    'max',
    'columns',
    'src',
    
    # Actions/Functions
    'action',
    'run',
    'return',
    'component',
    'use',
    'state',
}